Change for Removing Error local variable _BACKEND referenced before assignment
Normal Execution Getting Error:
```
  File "/home/a/honeypots/telnet-iot-honeypot/honeypot/sampledb_client.py", line 14, in get_backend
    if _BACKEND:
UnboundLocalError: local variable '_BACKEND' referenced before assignment
```
So this Fix.